classdef xyz_data < robotics.ros.Message
    %xyz_data MATLAB implementation of vn100imu/xyz_data
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'vn100imu/xyz_data' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'a7b495b29cdd1a4c83726ab10b5999e4' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsVector3Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Vector3') % Dispatch to MATLAB class for message type geometry_msgs/Vector3
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        XYZ
        Period
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'XYZ', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Period', 'XYZ'} % List of non-constant message properties
        ROSPropertyList = {'header', 'Period', 'XYZ'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = xyz_data(msg)
            %xyz_data Construct the message object xyz_data
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'xyz_data', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function xyz = get.XYZ(obj)
            %get.XYZ Get the value for property XYZ
            if isempty(obj.Cache.XYZ)
                obj.Cache.XYZ = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getXYZ);
            end
            xyz = obj.Cache.XYZ;
        end
        
        function set.XYZ(obj, xyz)
            %set.XYZ Set the value for property XYZ
            validateattributes(xyz, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'xyz_data', 'XYZ');
            
            obj.JavaMessage.setXYZ(xyz.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.XYZ)
                obj.Cache.XYZ.setJavaObject(xyz.getJavaObject);
            end
        end
        
        function period = get.Period(obj)
            %get.Period Get the value for property Period
            period = single(obj.JavaMessage.getPeriod);
        end
        
        function set.Period(obj, period)
            %set.Period Set the value for property Period
            validateattributes(period, {'numeric'}, {'nonempty', 'scalar'}, 'xyz_data', 'Period');
            
            obj.JavaMessage.setPeriod(period);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.XYZ = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Period = obj.Period;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.XYZ = copy(obj.XYZ);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Period = strObj.Period;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.XYZ = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.XYZ);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Period = obj.Period;
            strObj.Header = saveobj(obj.Header);
            strObj.XYZ = saveobj(obj.XYZ);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.vn100imu.xyz_data.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.vn100imu.xyz_data;
            obj.reload(strObj);
        end
    end
end
